import { addDays, format } from "date-fns";
import { TripPlan } from "@/lib/types";

export const samplePlan = {
  id: "trip-madrid-seoul-2026",
  name: "Madrid to Seoul: Hanok Experience",
  days: [
    {
      id: "day-1",
      date: "2026-05-02",
      city: "Madrid",
      label: "Flight to Seoul",
      activities: [
        {
          id: "m1",
          dayId: "day-1",
          city: "Madrid",
          title: "Vuelo a Seúl (Salida Barajas T1)",
          time: "13:10",
          durationMin: 720,
          category: "transport",
          priority: "critical",
          state: "pending",
          notes: "✈️ 13:10 → Salida Madrid T1. 🌙 → Noche en vuelo.",
          location: "Madrid Barajas T1",
        },
      ],
    },
    {
      id: "day-2",
      date: "2026-05-03",
      city: "Seoul",
      label: "Arrival & Hanok Magic",
      activities: [
        {
          id: "s1",
          dayId: "day-2",
          city: "Seoul",
          title: "Llegada a Gimpo Airport (GMP)",
          time: "13:05",
          durationMin: 60,
          category: "transport",
          priority: "critical",
          state: "pending",
          notes: "🛬 Trámites: inmigración + maletas. 💳 Tarea: sacar efectivo o activar eSIM. 🚕 Taxi recomendado por cansancio. ⏱️ Calcula salir sobre 14:00–14:15.",
        },
        {
          id: "s2",
          dayId: "day-2",
          city: "Seoul",
          title: "Traslado + Check-in Hanok Gongsimga",
          time: "14:15",
          durationMin: 75,
          category: "hotel",
          priority: "high",
          state: "pending",
          notes: "✨ Como duermes en hanok, este check-in es parte de la experiencia. 👉 Tómate 20–30 min para: fotos, cambiarte, ducha rápida, dejar maletas.",
          location: "Hanok Gongsimga",
        },
        {
          id: "s3",
          dayId: "day-2",
          city: "Seoul",
          title: "Café coreano / snack suave",
          time: "15:30",
          durationMin: 45,
          category: "food",
          priority: "medium",
          state: "pending",
          notes: "Zona ideal: Bukchon / Samcheong-dong / Ikseondong. 🍰 Plan perfecto: latte, croffle, tarta coreana, café aesthetic. 💡 Ayuda con el jet lag.",
        },
        {
          id: "s4",
          dayId: "day-2",
          city: "Seoul",
          title: "Bukchon Hanok Village Walk",
          time: "16:30",
          durationMin: 90,
          category: "sightseeing",
          priority: "high",
          state: "pending",
          notes: "✨ MUCHO mejor hacerlo hoy que mañana. 📸 Fotos top: calle con tejados, vistas hacia N Seoul Tower, callejones altos.",
          location: "Bukchon Hanok Village",
        },
        {
          id: "s5",
          dayId: "day-2",
          city: "Seoul",
          title: "Ikseondong + Insadong (Luces)",
          time: "18:15",
          durationMin: 75,
          category: "shopping",
          priority: "medium",
          state: "pending",
          notes: "🏮 Brutal de noche: compras, souvenirs, tea houses, luces, cosmética coreana. 👉 Cero repetición con días futuros.",
        },
        {
          id: "s6",
          dayId: "day-2",
          city: "Seoul",
          title: "Cena en Insadong / Ikseondong",
          time: "19:30",
          durationMin: 90,
          category: "food",
          priority: "medium",
          state: "pending",
          notes: "🍗 Vibes: Fried chicken, galbi, kalguksu o mandu. 💡 Mejor algo rico pero no pesado por el vuelo.",
        },
        {
          id: "s7",
          dayId: "day-2",
          city: "Seoul",
          title: "Regreso al Hanok",
          time: "21:00",
          durationMin: 30,
          category: "hotel",
          priority: "low",
          state: "pending",
          notes: "🌙 MUY importante dormir bien porque mañana optimizaremos el Palacio + Hanbok.",
        },
      ],
    },
    {
      id: "day-3",
      date: "2026-05-04",
      city: "Seoul",
      label: "Palace + Modern Seoul",
      activities: [
        {
          id: "s8",
          dayId: "day-3",
          city: "Seoul",
          title: "Desayuno temprano",
          time: "08:00",
          durationMin: 40,
          category: "food",
          priority: "medium",
          state: "pending",
          notes: "💡 Egg drop, café, pastry coreano. 👉 Importante salir antes de las 9.",
        },
        {
          id: "s9",
          dayId: "day-3",
          city: "Seoul",
          title: "Hanbok Rental",
          time: "08:45",
          durationMin: 15,
          category: "reservation",
          priority: "high",
          state: "pending",
          notes: "👘 Al lado del palacio. Llegar 15 min antes. 👉 Mejor reservar por Klook.",
          location: "36, Yulgok-ro 1-gil, Jongno-gu, Seoul",
        },
        {
          id: "s10",
          dayId: "day-3",
          city: "Seoul",
          title: "Gyeongbokgung Palace",
          time: "09:00",
          durationMin: 120,
          category: "sightseeing",
          priority: "critical",
          state: "pending",
          notes: "🏯 Mejor momento: menos grupos, mejor luz. 📸 Spots: pabellón del lago, patio principal. 💡 Con hanbok es GRATIS.",
          location: "Gyeongbokgung Palace",
        },
        {
          id: "s11",
          dayId: "day-3",
          city: "Seoul",
          title: "Traslado + Check-in OYO Myeongdong 6",
          time: "11:30",
          durationMin: 60,
          category: "hotel",
          priority: "high",
          state: "pending",
          notes: "🏨 Dejas maletas y te cambias del hanbok sin cargar todo el día.",
          location: "OYO Myeongdong 6",
        },
        {
          id: "s12",
          dayId: "day-3",
          city: "Seoul",
          title: "Almuerzo Myeongdong",
          time: "12:45",
          durationMin: 45,
          category: "food",
          priority: "medium",
          state: "pending",
          notes: "🍜 Kalguksu, mandu o Fried Chicken.",
        },
        {
          id: "s13",
          dayId: "day-3",
          city: "Seoul",
          title: "Gangnam + Starfield Library + COEX",
          time: "14:15",
          durationMin: 165,
          category: "shopping",
          priority: "medium",
          state: "pending",
          notes: "📚 Starfield Library, 🛍️ COEX Mall, 👟 Sneakers, 🎁 K-pop. 💡 Aquí mete el shopping fuerte.",
        },
        {
          id: "s14",
          dayId: "day-3",
          city: "Seoul",
          title: "N Seoul Tower Sunset + Sky",
          time: "17:15",
          durationMin: 165,
          category: "reservation",
          priority: "high",
          state: "pending",
          notes: "🌆 Cable car, mirador sunset, candados, skyline nocturno. 🎟️ Recoger ticket en 1 Floor, 15 Toegye-ro 14-gil (Rednow Studio).",
          location: "N Seoul Tower",
        },
        {
          id: "s15",
          dayId: "day-3",
          city: "Seoul",
          title: "Cena con vista nocturna",
          time: "20:00",
          durationMin: 90,
          category: "food",
          priority: "medium",
          state: "pending",
          notes: "🌃 N Seoul Tower restaurants / Myeongdong rooftop. 💡 Premium: n.GRILL.",
        },
      ],
    },
    {
      id: "day-4",
      date: "2026-05-05",
      city: "Seoul",
      label: "Foodie + Relax + Hongdae",
      activities: [
        {
          id: "s16",
          dayId: "day-4",
          city: "Seoul",
          title: "COLORIZE MYEONGDONG",
          time: "09:00",
          durationMin: 80,
          category: "reservation",
          priority: "high",
          state: "pending",
          notes: "🎨 Regalo: Análisis de color personal, maquillaje recomendado. 👨 Paseo corto cerca.",
          location: "Colorize Myeongdong",
        },
        {
          id: "s17",
          dayId: "day-4",
          city: "Seoul",
          title: "Gwangjang Market (Foodie Lunch)",
          time: "11:15",
          durationMin: 75,
          category: "food",
          priority: "high",
          state: "pending",
          notes: "🥟 Mandu, bindaetteok, mayak kimbap. 📸 Vibe mercado real.",
          location: "Gwangjang Market",
        },
        {
          id: "s18",
          dayId: "day-4",
          city: "Seoul",
          title: "Cheonggyecheon + Euljiro Walk",
          time: "12:30",
          durationMin: 60,
          category: "sightseeing",
          priority: "low",
          state: "pending",
          notes: "🌊 Río urbano + callejones industriales aesthetic.",
        },
        {
          id: "s19",
          dayId: "day-4",
          city: "Seoul",
          title: "Hotel Break (CLAVE)",
          time: "13:45",
          durationMin: 105,
          category: "hotel",
          priority: "medium",
          state: "pending",
          notes: "🏨 Organizar maleta (mañana Osaka), siesta corta, descanso de piernas.",
        },
        {
          id: "s20",
          dayId: "day-4",
          city: "Seoul",
          title: "Hongdae Street Vibes",
          time: "16:00",
          durationMin: 210,
          category: "nightlife",
          priority: "high",
          state: "pending",
          notes: "🎶 Street performances, moda, skincare, ambiente joven. 🍗 Cena opcional fried chicken.",
          location: "Hongdae",
        },
      ],
    },
  ],
  criticalReservations: [
    {
      id: "r1",
      title: "Hanbok Rental (Klook)",
      bookingDeadline: "2026-04-20",
      reservationDate: "2026-05-04",
      bookingLink: "https://www.klook.com/activity/2764-hanbok-rental-gyeongbokgung-seoul/",
      urgency: "safe",
      status: "booked",
      price: 15,
      cancellationNotes: "Free cancellation 24h before",
    },
    {
      id: "r2",
      title: "N Seoul Tower (Klook)",
      bookingDeadline: "2026-04-20",
      reservationDate: "2026-05-04",
      bookingLink: "https://www.klook.com/activity/430-n-seoul-tower-admission-ticket-seoul/",
      urgency: "safe",
      status: "booked",
      price: 10,
    },
  ],
} as unknown as TripPlan;
